<template>
  <div class="results">
    <h2>Your Energy Efficiency Recommendations</h2>

    <div class="summary-box">
      <h3>Summary</h3>
      <p>{{ advice.summary }}</p>
      <p v-if="advice.estimated_total_annual_savings" class="total-savings">
        💰 Estimated Total Annual Savings: €{{ advice.estimated_total_annual_savings.toFixed(2) }}
      </p>
      <p class="metadata">
        Generated by {{ advice.llm_provider }} on {{ formattedDate }}
      </p>
    </div>

    <h3>Recommendations ({{ advice.recommendations.length }})</h3>
    <div class="recommendations">
      <RecommendationCard 
        v-for="(rec, index) in advice.recommendations"
        :key="index"
        :recommendation="rec"
      />
    </div>

    <button @click="$emit('reset')" class="reset-button">
      🔄 Analyze Another Home
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { EnergyAdvice } from '../types';
import RecommendationCard from './RecommendationCard.vue';

interface Props {
  advice: EnergyAdvice;
}

interface Emits {
  (e: 'reset'): void;
}

const props = defineProps<Props>();
defineEmits<Emits>();

const formattedDate = computed(() => {
  return new Date(props.advice.generated_at).toLocaleString();
});
</script>

<style scoped>
.results {
  animation: fadeIn 0.5s ease-in;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.summary-box {
  background: linear-gradient(135deg, #e8eaf6 0%, #c5cae9 100%);
  color: #37474f;
  padding: 2rem;
  border-radius: 12px;
  margin-bottom: 2rem;
  box-shadow: 0 4px 16px rgba(63, 81, 181, 0.15);
}

.summary-box h3 {
  margin-top: 0;
  margin-bottom: 1rem;
  font-size: 1.5rem;
  color: #3f51b5;
}

.summary-box p {
  line-height: 1.6;
  margin-bottom: 1rem;
}

.total-savings {
  font-size: 1.3rem;
  font-weight: 600;
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid rgba(63, 81, 181, 0.2);
  color: #3f51b5;
}

.metadata {
  font-size: 0.85rem;
  opacity: 0.7;
  margin-top: 0.5rem;
  margin-bottom: 0 !important;
  color: #546e7a;
}

.recommendations {
  display: grid;
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.reset-button {
  width: 100%;
  padding: 1rem 2rem;
  background: linear-gradient(135deg, #5c6bc0 0%, #3f51b5 100%);
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 1.1rem;
  font-weight: 600;
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s;
  margin-top: 2rem;
}

.reset-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(63, 81, 181, 0.3);
}
</style>
