"""Application-wide constants"""

# LLM Configuration
LLM_TEMPERATURE = 0.7
LLM_MAX_TOKENS = 4000
LLM_TIMEOUT_SECONDS = 120
LLM_RETRY_ATTEMPTS = 3
LLM_RETRY_MIN_WAIT = 1
LLM_RETRY_MAX_WAIT = 10

# Logging
LOG_RESPONSE_PREVIEW_LENGTH = 200

# Financial Thresholds (EUR)
ZERO_VALUE_THRESHOLD = 0

# Budget Ranges (EUR)
BUDGET_LOW_MAX = 5_000
BUDGET_MEDIUM_MIN = 5_000
BUDGET_MEDIUM_MAX = 15_000
BUDGET_HIGH_MIN = 15_000
BUDGET_HIGH_MAX = 50_000
BUDGET_PREMIUM_MIN = 50_000
